defaults: &defaults
  adapter: mysql2
  encoding: utf8
  pool: 5
  reconnect: false
  database: my_app_db
  username: root
  password: 6kuLqDLCaV
  host: mysql-giba-ruby.jelasticlw.com.br
  port: 3306

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
